Removed use of `my $_` (#1)
This addresses the error,

    Error: Can't use global $_ in "my" ...

As seen in the following CPAN Testers report.

http://www.cpantesters.org/cpan/report/8b13e906-6935-11e5-98c1-2ff5d0d03245

Apparently, as of Perl 5.23.4, this has been promoted from a warning to
an error.